name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: o-an-quan-ai

      - name: Configure Docker to use gcloud as a credential helper
        run: gcloud auth configure-docker --quiet

      - name: Build and push backend Docker image
        run: |
          docker build -t huyenngn/backend-api -f Dockerfile .
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u huyenngn --password-stdin
          docker push huyenngn/backend-api

      - name: Build and push frontend Docker image
        run: |
          docker build \
            --build-arg VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }} \
            --build-arg VITE_SUPABASE_KEY=${{ secrets.VITE_SUPABASE_KEY }} \
            --build-arg VITE_API_URL=${{ secrets.VITE_API_URL }} \
            -t huyenngn/frontend -f frontend/Dockerfile ./frontend
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u huyenngn --password-stdin
          docker push huyenngn/frontend

      - name: Deploy backend to Cloud Run (us-central1)
        run: |
          gcloud run deploy backend-api-us-central1 \
            --image huyenngn/backend-api \
            --platform managed \
            --region us-central1 \
            --project o-an-quan-ai \
            --allow-unauthenticated

      - name: Deploy backend to Cloud Run (europe-west4)
        run: |
          gcloud run deploy backend-api-europe-west4 \
            --image huyenngn/backend-api \
            --platform managed \
            --region europe-west4 \
            --project o-an-quan-ai \
            --allow-unauthenticated

      - name: Deploy backend to Cloud Run (asia-east1)
        run: |
          gcloud run deploy backend-api-asia-east1 \
            --image huyenngn/backend-api \
            --platform managed \
            --region asia-east1 \
            --project o-an-quan-ai \
            --allow-unauthenticated

      - name: Deploy frontend to Cloud Run
        run: |
          gcloud run deploy frontend \
            --image huyenngn/frontend \
            --platform managed \
            --region europe-west4 \
            --project o-an-quan-ai \
            --allow-unauthenticated
