name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push backend Docker image
        run: |
          docker build -t huyenngn/backend-api -f Dockerfile .
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u huyenngn --password-stdin
          docker push huyenngn/backend-api

      - name: Build and push frontend Docker image
        run: |
          docker build \
            --build-arg VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }} \
            --build-arg VITE_SUPABASE_KEY=${{ secrets.VITE_SUPABASE_KEY }} \
            --build-arg VITE_BACKEND_US=${{ secrets.VITE_BACKEND_US }} \
            --build-arg VITE_BACKEND_EU=${{ secrets.VITE_BACKEND_EU }} \
            --build-arg VITE_BACKEND_ASIA=${{ secrets.VITE_BACKEND_ASIA }} \
            -t huyenngn/frontend -f frontend/Dockerfile ./frontend
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u huyenngn --password-stdin
          docker push huyenngn/frontend
